[font]
size = 16
offset = { x = 0, y = 4 }
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular"}
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "SemiBold"}
italic = { family = "Victor Mono", style = "Italic"}
