[font]
size = 18
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Light"}
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "SemiBold"}
italic = { family = "Victor Mono", style = "Italic"}
